only change values.yml ref: master to PR if repo is pelorus (#525)
when testing w/ openshift/release things were failing because the
change ref was from release and not pelorus.  Causing:
Cloning "https://github.com/konveyor/pelorus.git" ...
error: fatal: couldn't find remote ref refs/pull/29693/head